# Generated by Django 2.1.3 on 2018-11-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.CharField(default='Course Name', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='lecturer',
            field=models.CharField(default='John Doe', max_length=50),
        ),
    ]
